### ISSUE TITLE
Any reason for not using camera2 api in this project?

### ISSUE THREAD

**Issue by srikar8** [rpng/android_sensors_driver#2]

**Comment by goldbattle** [comment]
This was made to work on the older Tango devices which only support the camera 1 api.
If you want to upgrade this to the camera 2 api, you can take a look at our [android-camera-calibration](https://github.com/rpng/android-camera-calibration) repository for an example or search online.

**Comment by srikar8** [comment]
OK. I will upgrade to camera2 api.
thank you for quick responds.
